@startuml design

package matches {
  class match
}

package auctions {
  class auction
  class bid

  auction --> bid
}

package card {
  class card
}

package user {
  class user
}

user --> auction : places bids
user --> card : owns
user --> match : competes at

@enduml